name: madgen
channels:
  - conda-forge
  - pytorch
  - nvidia/label/cuda-12.1.0
  - defaults
dependencies:
  - python=3.9
  - rdkit
  - pytorch=2.1
  - torchvision
  - torchaudio
  - pip
  - pip:
      - aiohttp==3.9
      - attrs==23.2
      - black==24.4
      - cattrs==23.2
      - charset-normalizer==2.1
      - click==8.1
      - fsspec==2024.3
      - gitpython==3.1
      - huggingface-hub==0.24
      - idna==3.7
      - imageio==2.31
      - joblib==1.4
      - lxml==4.9
      - markupsafe==2.1
      - matchms==0.27
      - matplotlib==3.7
      - myopic-mces==1.0
      - networkx==3.2
      - numpy==1.26
      - packaging==24.1
      - pandas==2.2
      - pathspec==0.12
      - protobuf==4.25
      - psutil==5.9
      - pulp==2.8
      - pytorch-lightning==2.0
      - requests==2.32
      - scikit-learn==1.4
      - scipy==1.11
      - seaborn==0.13
      - selfies==2.1
      - sentry-sdk==1.45
      - torch-geometric==2.3
      - torchmetrics==0.11
      - tqdm==4.66
      - typing-extensions==4.12
      - urllib3==1.26
      - wandb==0.15
      - zipp==3.18