# General
experiment_name: madgen_msgym
checkpoints: checkpoints
logs: logs
data: data
wandb_entity: null
seed: 42
device: gpu

# Settings
sample_every_val: 50
log_every_steps: 40
samples_to_generate: 128
samples_to_save: 128
samples_per_input: 5
chains_to_save: 5
number_chain_steps_to_save: 40
enable_progress_bar: True

# Data
dataset: msgym
batch_size: 256
num_workers: 47
shuffle: True
extra_nodes: True
swap: False

# Diffusion
diffusion_steps: 50
diffusion_noise_schedule: cosine
transition: null
fix_product_nodes: True

# Model
use_context: True
extra_features: all
extra_molecular_features: False
n_layers: 5
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128, 's': 256}
hidden_dims: {'dx': 64, 'de': 64, 'dy': 64, 'ds': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

# Training
n_epochs: 2000
lambda_train: [5, 0]
lr: 0.00001
weight_decay: 0.000000000001
loss_type: vlb
condition: True

# Checkpoint
resume: 
